### PR TITLE
Hobbit Research

### LINKED ISSUE #4: Research blocking
Add structures and furniture behind research wall.

### PR DESCRIPTION
**Pull request by RodEsp**
This is a work in progress to make research necessary for Hobbit items instead of having them available by default from the start.

Fixes #4

### CODE REVIEW

**Comment by RodEsp** [comment]
Ok, this should be good to go! I'm pretty sure that's all of the Hobbit things, there aren't too many.

**Comment by RodEsp** [comment]
Wait a second... [Pipe-weed Pipes](https://github.com/Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Hobbits/blob/master/Defs/Drugs/LotRH_PipeweedPipe.xml#L4) and [Pipe-weed Packs](https://github.com/Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Hobbits/blob/master/Defs/RecipeDefs/LotRH_PipeweedPipes.xml) should probably be researchable too...

**Comment by RodEsp** [comment]
Ok, this is officially ready @jecrell! :)

**Comment by jecrell** [comment]
Awesome. I'll run a test on it now.

**Comment by jecrell** [comment]
Existing hobbit saves continue to load without errors after applying the new pull request.
Merging request and pushing to upload.

**Pull request merged**
